title: pejman
description: pej-man's Personal Website
baseurl: ""

username: pejman montazeri
typing_text: Front-end / Back-end Developer

email: pejmanly@gmail.com
telegram_username: pejgman
linkedin_username: mohamad-hosein-montazeri
github_username: pej-man
instagram_username: i._.pejman

show_aboutme_card: false
about_me_title: About Me
about_me_description: I would introduce myself as a full-stack developer with expertise in Laravel, Python, and React, as well as a strong command of HTML, CSS, and JavaScript. I have experience working with MySQL and MongoDB databases, and I am skilled in RESTful API structure. I am confident in my abilities as a developer and am always eager to learn new technologies and expand my skill set.

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience

show_projects_card: true
show_projects: false
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: insolitum/insolitum.github.io
github_pages:
  - sorting_algos
  - character_encoder
  - insolitum.github.io
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - insolitum

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
